import Mathlib

/-- Constraint set generated by finitely many weak inequality constraints. -/
def convex_constraint_set {n m : ℕ}
    (constraints : Fin m → (Fin n → ℝ) → ℝ) : Set (Fin n → ℝ) :=
  {x | ∀ i, constraints i x ≤ 0}
